### PR TITLE
#1280 footer issue update

### PR DESCRIPTION
**Pull request by Code-Ebullient**
Signed-off-by: Peace <newchassis.pa@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by ashiscs** [comment]
@Code-Ebullient , one suggestion
Try to mention the issue number the pr fixes so that the issue gets automatically closed on merging the pr [example = fixes #issue_number].
Between nice work !

**Comment by Ruth-ikegah** [comment]
Nice work @Code-Ebullient

**Comment by leecalcote** [comment]
@Code-Ebullient, at risk of giving you the same memo that @ashiscs did, here's reference to what @ashiscs is highlighting - https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords

On the chance that you've ever seen Office Space (the movie): https://www.youtube.com/watch?v=8bchnLOT7ic

**Comment by leecalcote** [comment]
Whoo-hoo! 🎈 @Code-Ebullient 😄

**Pull request merged**
